export const SURVEYS = 'FETCH_SURVEYS';
export const SINGLE_SURVEY = 'SINGLE_SURVEY';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const SURVEYS_ERROR = 'SURVEYS_ERROR';
export const SURVEY_ERROR = 'SURVEY_ERROR';
export const SUBMIT_ERROR = 'SUBMIT_ERROR';
